# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7a78a1f7031a306202f377132cc8da811fa69a7d9144bf0d4d566ee3889ef073f51a028414ff6e3e452a0e9dec8f0f118ed64d1582eb3665417390b8efe5b29

test:
  secret_key_base: f0d5cc9e05b1c737acf8c62dd401d7ec45d1c37b73fd02003c694c69146849dfbeb4de8647cfd071b994ef858372cfa1c9f2c2d650bf1713701b48262cba920e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: efe71e1ad4fb5983e53d1c5b956367d2368e32d56ef83cb2117ce3a049588bf64f7e0089dc808ef935e90c80e4e4fc75aff6de7665174f023801b82342dacb00
